spring.application.name=ProjetoQuestionario

server.servlet.context-path=/projetoquestionario

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ProjetoQuestionario
spring.datasource.username=postgres
spring.datasource.password=murilo123

# por enquanto, ainda n�o estamos utilizando o flyway
spring.flyway.enabled=false

#recomendação do gemini isso pra baixo enqt n usa o flyway

# Faz o Hibernate criar as tabelas sozinho baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra no console do VS Code os comandos SQL que o Spring está fazendo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate use o dialeto correto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# desabilitando o console H2
spring.h2.console.enabled=false